MCU_LDSCRIPT = STM32F405xG_tinyuf2
FIRMWARE_FORMAT = uf2
UF2_FAMILY = STM32F4

I2C_DRIVER_REQUIRED = yes
RGB_INDICATOR_ENABLE = yes
QUANTUM_LIB_SRC += \
	color.c \

DEBOUNCE_TYPE = asym_eager_defer_pk
