// Copyright 2026 weimao (@luantty2)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define BLUEISM_UART_CMD_SYS_PING 0x11
#define BLUEISM_UART_CMD_SYS_RESET 0x12
#define BLUEISM_UART_CMD_SYS_GET_VERSION 0x13

#define BLUEISM_UART_CMD_BLE_SELECT_ID 0x21
#define BLUEISM_UART_CMD_BLE_SELECT_DONGLE 0x22
#define BLUEISM_UART_CMD_BLE_ERASE_BOND 0x23

#define BLUEISM_UART_CMD_HID_6KRO 0x31
#define BLUEISM_UART_CMD_HID_NKRO 0x32
#define BLUEISM_UART_CMD_HID_CONSUMER_CTRL 0x33
#define BLUEISM_UART_CMD_HID_SYSTEM_CTRL 0x34
#define BLUEISM_UART_CMD_HID_MOUSE 0x35
#define BLUEISM_UART_CMD_HID_BATTERY 0x36
#define BLUEISM_UART_CMD_HID_KEYBOARD_LEDS 0x37

#define BLUEISM_HID_LED_NUM_LOCK (1U << 0)
#define BLUEISM_HID_LED_CAPS_LOCK (1U << 1)
#define BLUEISM_HID_LED_SCROLL_LOCK (1U << 2)
#define BLUEISM_HID_LED_COMPOSE (1U << 3)
#define BLUEISM_HID_LED_KANA (1U << 4)
